---
title: 'Lab 1: Git & Github'
author: "ES _____"
date: 
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
  word_document: default
---
# Overview
In this we will focus on setting up R, RStudio, Git, Github,  and Sourcetree. Utilizing 

R is a command-line interface that forces you to program your own analyses in a script. While this can be initimidating at first, it pays quickly to learn how to script your analyses when you have to redo your analysis if you discover a mistake, provide documentation, transparency and reproducibility of analyses, perform similar workflows, or perform batch prcessing. 

RStudio is a free and open-source integrated development environment for R, a programming language for statistical computing and graphics.

Git and Github are version control systems for tracking changes in computer files and coordinating work on those files among multiple people.

SourceTree is a Git GUI that offers a visual representation of your repositories.



## How These Tutorials Work
Because we are working with open source software, there are far more useful and varied examples online than we can possibly cover in this class. Part of learning open source software is by reading different turorials, blog posts, and other resources. I will post required and suggested reading, but you should consider these as springboards only. With a little bit of internet research, you can acheive far more than what these basic tutorials cover.

Sometimes I will give you instruction and examples in these tutorials, and sometimes I will point you to other online tutorials that you will have to complete. Note the learning objectives for each tutorial. These will be part of the overall course objectives, and will be covered in exams. 

## Lab Assignments
For each lab assignment I will ask you to demonstrate that you have done different pieces of the work, by prodviding maps or screen shots of images, plots or statistics calcuated from images, and some basic short writing and answering of questions. 
In each section, if the text is

><span style="color:CRIMSON;">CRIMSON like
this it indicates a prompt for a question that you *must* answer or a product you must turn in for your lab assignment. Crimson blocks of text are action items for you!</span> 

# Objectives  
After this lab, you will:  

* Have the majority of software for this class installed and ready to use
* Know how to utilize features of Git and Github manage version control of your code an share it.

## Helpful Terminology

Github has a glossary that will help in learning the lingo. It can be found here: https://help.github.com/articles/github-glossary/

# Assignment:

A great tutorial for using Git and Github with R can be found here http://happygitwithr.com/ 

Work through The Happy Git with R tutorial, ensuring you complete the steps below.


><span style="color:CRIMSON;">1. Complete Steps 1-28 in the "Happy Git with R" tutorial.</span>

><span style="color:CRIMSON;">2. In step 9 install SourceTree. Note: If you're using google chrome with a google account, and also use a google account for registering with Atlassian it makes life easy. You will not need to worry about setting up HTTPS or SSH authorization to make push and pull requests. </span>

><span style="color:CRIMSON;">3. Make a repo on GitHub called "____hw1. Write the render-read R script in 20.2 and commit it to your repo.</span>

><span style="color:CRIMSON;">4. Following the instructions in 23, clone a GitHub repository that interests you. Find one script in the repo and run the code locally and understand what it is doing. Once you understand what it is doing, document this in a R Notebook using RMarkdown and commit it to your hw1 repo. Make sure to cite the source of your script, and document any changes you made. DO NOT fork this code (we will do that next time).</span>

><span style="color:CRIMSON;">5. Following the instructions in 25, fork the 'bingo' repo. Clone it to your local machine and create a new bingo card. Commit and push your changes back to your copy of the repo on GitHub. Make a pull request back to the main 'bingo' repo.</span>

><span style="color:CRIMSON;">6. Following the instructions in 26, Burn it all down.</span>

><span style="color:CRIMSON;">7. Following the instructions in 26, Burn it all down.</span>

><span style="color:CRIMSON;">8. Email your instructor with your GitHub repo. Place in the subject line: "ES207 yourname GitHub". Place in the message your GitHub page: "https://github.com/yourname/___hw1"</span>


## Using SourceTree 

Sourcetree is an easy to use GUI that will reduce tediousness of using command line.

One place it makes things significantly easier is updating a copy of a repository that you have forked. For example, in step _ of the Happy Git with R, you add another remote. This can be done much easier and visualized in sourcetree. In this section we will Fork a repository, clone it to the local machine, and then update the forked repo and the local clone from an updated origal repository.

Step 1: Go onto github and fork this repository: **https://github.com/ebolch/ES295** This will be the repository used for the class, and you can easily download and update files as they are added throughout the semester by using the following procedure.

Step 2: Launch Sourcetree, then go to File > New. Clone the repository you just forked by pasting the URL into the Sourcepath/URL box. After that, set up the local directory you want to save the files in and click the clone button. 

Now you have a copy of the repository you forked on your local computer. Assume the some of the original code you forked has been updated and you want the new versions. To get them, you can add a remote easily in Sourcetree.

Step 3: Add a remote by going to Repository > add Remote... Then click the add button, name your remote, and paste the original URL which you forked into the URL/Path field. 

Step 4: Now that you've added another remote you can easily update your local files and push them onto your Github. Click the pull button, then choose the new remote that you added from the dropdown box, and the branch that you want to update. Check the boxes below for the options you want to use, then click ok to update your local files.

Step 5: You now have the updated files on your local pc, but not in your forked repository on Github. To upload the files, click the push button and select the repository and then click the push button. This will upload the updated local files to your github repository.



